CAMERA_FPS = 50

SPEED_TRIM = 0.5
SPEED_TRIM_AI = 1.0

LOG_DIR = './log/'
MODEL_FILE = './model.tflite'

PWM_WHEEL_CENTER = 1519
PWM_WHEEL_RIGHT = 1959
PWM_WHEEL_LEFT = 1099

PWM_TRIGGER_CENTER = 1499
PWM_TRIGGER_FORWARD = 1946
PWM_TRIGGER_REVERSE = 1082

#GPIO NUMBER
GPIO_WHEEL = 20
GPIO_TRIGGER = 26

GPIO_SERVO = 12
GPIO_ESC = 13

GPIO_BTN_A = 25
GPIO_BTN_B = 8
GPIO_BTN_C = 6

GPIO_LED_A = 24
GPIO_LED_B = 7
GPIO_LED_C = 5

CAM_ROTATE = False #True or False

FRAME_WIDTH = 160
FRAME_HEIGHT = 80
